/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/../src/utils/translations`; params?: Router.UnknownInputParams; } | { pathname: `/../src/utils/LanguageContext`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/PolicyScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/ClaimStatusScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/OnboardingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/claims` | `/claims`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/policy` | `/policy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/utils/translations`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/utils/LanguageContext`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/screens/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/screens/PolicyScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/screens/ClaimStatusScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/screens/ProfileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/screens/OnboardingScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/claims` | `/claims`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/policy` | `/policy`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/../src/utils/translations${`?${string}` | `#${string}` | ''}` | `/../src/utils/LanguageContext${`?${string}` | `#${string}` | ''}` | `/../src/screens/HomeScreen${`?${string}` | `#${string}` | ''}` | `/../src/screens/PolicyScreen${`?${string}` | `#${string}` | ''}` | `/../src/screens/ClaimStatusScreen${`?${string}` | `#${string}` | ''}` | `/../src/screens/ProfileScreen${`?${string}` | `#${string}` | ''}` | `/../src/screens/OnboardingScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/claims${`?${string}` | `#${string}` | ''}` | `/claims${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/policy${`?${string}` | `#${string}` | ''}` | `/policy${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/../src/utils/translations`; params?: Router.UnknownInputParams; } | { pathname: `/../src/utils/LanguageContext`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/PolicyScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/ClaimStatusScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/OnboardingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/claims` | `/claims`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/policy` | `/policy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
